### ISSUE TITLE
Reconsider `highway=service` in Polygon Whitelist

### ISSUE THREAD

**Issue by mykolakozyr** [aspectumapp/osm2geojson#1]
### Description

There is `highway=service` in Polygon Whitelist, while "*The tag highway=service predominantly describes a linear feature of a routable way. When mapped as a closed polygon without any further tagging, it describes a linear, circular way and not an area.*" [[OSM Wiki]](https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice)

In cases using `service=` tag with highways, it is usually used with the following tags (all of them are **linear** objects [[OSM Wiki]](https://wiki.openstreetmap.org/wiki/Key:service):

- service=parking_aisle
- service=driveway
- service=alley
- service=emergency_access for firefighters
- service=drive-through
- service=User Defined

The issue appeared with no possibility to transform `bridges` geometry to lines due to the conditions described.  

### Proposed solution
**Remove `highway=service` from Polygon Whitelist**

**Comment by rapkin** [comment]
I found in OSM documentation two types of tags:

 * `highway=service` - https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservice (your first link)
 * `highway=services` - https://wiki.openstreetmap.org/wiki/Tag:highway%3Dservices . You also can read 'Notes' section by this link.

This is important in our case. As you can see in this lib I use `polygon-features.json` to detect polygons: https://github.com/tyrasd/osm-polygon-features/blob/65e0a1e290675877e8cdd007efcefc35a7dfe0dc/polygon-features.json . And there is only `highway=services` in whitelist (this is correct by OSM documentation).

If you have any problem with polygons generation, please, describe your problem with example.

**Comment by mykolakozyr** [comment]
My fault :)
