### ISSUE TITLE
Dependencies error

### ISSUE THREAD

**Issue by isjeffcom** [aspectumapp/osm2geojson#11]
FileNotFoundError: Could not find module 'C:\Users\wjf46\miniconda3\envs\CUBE-Server\Library\bin\geos_c.dll' (or one of its dependencies). Try using the full path with constructor syntax.

**Comment by rapkin** [comment]
It's problem with geos extension (shapely use it). I can't fix this in my package. You can read more about shapely installation on Windows. Also here similar issue https://github.com/Toblerity/Shapely/issues/343
