### ISSUE TITLE
json2geojson results in segmentation fault

### ISSUE THREAD

**Issue by tgeasley** [aspectumapp/osm2geojson#20]
Attempting to run the following code:

```
import json
import requests
import osm2geojson as o2gj
#import geopandas as gpd

overpass_url = "http://overpass-api.de/api/interpreter"
overpass_query = """
[out:json][timeout:9000][maxsize:1073741824];
(
 way[highway~"^(primary|primary_link|secondary|secondary_link|tertiary|tertiary_link|unclassified|residential)$"](around:1000,26.078471,-80.245360);

);
(._;>;);out;
"""
response = requests.get(overpass_url, 
                        params={'data': overpass_query})

geoJson = o2gj.json2geojson(response.json())
```

Resulted in:

`Segmentation fault` 

With no further information provided. I attempted the solution noted in: https://github.com/aspectumapp/osm2geojson/issues/19

but the issue continued to occur.

**Comment by rapkin** [comment]
Can you provide full console output (with stacktrace)?

**Comment by tgeasley** [comment]
Right now I'm not getting any stacktrace with it.  When I try and run all I'm getting is:
```
$ /anaconda3/bin/python /python_scripts/2021_03_19_overpass_tt/overpass_fetch.py
Segmentation fault
```

I tried modifying the code with some try/except to get the stacktrace but it doesn't catch it as an error.

**Comment by tgeasley** [comment]
Okay, ran it in gdb and got the following, if this is useful:

```
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[Detaching after fork from child process 12559]

Program received signal SIGSEGV, Segmentation fault.
0x00007fffe8338d0d in GEOSCoordSeq_create_r () from /home/tgeasley/anaconda3/lib/python3.8/site-packages/shapely/speedups/../../../../libgeos_c.so.1
```

**Comment by rapkin** [comment]
As you can see `libgeos` produces seg-fault, so problem on side of C-extension used by shapely.
You can try to use this commands to reinstall shapely (for pip):

```
pip uninstall shapely
pip install --no-binary :all: shapely
```

**Comment by tgeasley** [comment]
Okay, yep, that fixed it.  For whatever reason going through conda was causing the issues.
