### ISSUE TITLE
Converting poligons and swapping/reordering issue

### ISSUE THREAD

**Issue by cad0p** [aspectumapp/osm2geojson#22]
Hi,
I had to solve the issue of converting polygons of boundaries for municipalities but I was writing in Python, so I'm sharing here my solution for the need of swapping and reordering Polygons:
https://gist.github.com/cad0p/463c805d93f48351d824e46cb8c98af6

![arenzano_bad](https://user-images.githubusercontent.com/14107574/124910379-d2178f00-dfeb-11eb-8c35-d73dae6992ee.png)
![rapallo_bad](https://user-images.githubusercontent.com/14107574/124910403-d774d980-dfeb-11eb-8175-5ac56b29d903.png)

Let me know if this is useful!

**Comment by rapkin** [comment]
Hi. You mean that output of osm2geojson have problems with converting to polygon?

**Comment by cad0p** [comment]
Hi, I haven't tested osm2geojson since it starts from xml instead of json

**Comment by rapkin** [comment]
I should say that JSON !== GeoJSON. Osm2geojson uses XML or JSON as input format (XML and JSON from Overpass). Also osm2geojson uses Shapely to cope with complex situations with geometry. So I don't think that your solution is relevant for this project :)
