### ISSUE TITLE
Troubles with xml2geojson

### ISSUE THREAD

**Issue by valluzzi** [aspectumapp/osm2geojson#23]
Hi, 
I have some troubles with the following query:
```
from osm2geojson import *
query="""[out:xml][timeout:60];
(
  // query part for: "building"
  way["building"](poly:"44.0602 12.5646 44.0608 12.5646 44.0612 12.5650 44.0595 12.5693 44.05860 12.5656");
);
out geom;
"""
xml = overpass_call(query)
features = xml2geojson(xml, filter_used_refs=False)
print(features)
```

the output is NO features while in the xml there are 8 features and also https://overpass-turbo.eu/ can see the buildings.

Am I doing something wrong?

Thank you for osm2geojson!

**Comment by rapkin** [comment]
Hi! I tested you example with last version and it works as expected.

![image](https://user-images.githubusercontent.com/5012778/126698010-de5f1287-3fc3-4ade-b498-76ff2a19fa1a.png)

![image](https://user-images.githubusercontent.com/5012778/126698239-2c822df9-530e-4414-b836-37d901f95b4d.png)

**Comment by valluzzi** [comment]
That's true!, I cant understand why this part of code doesnt worked in another section of my code. I am sorry for the false alarm. thank you again.

**Comment by valluzzi** [comment]
finally I have found that there is some kind of interference with osgeo package
the first line `from osgeo import ogr`  make this code not working  as expected.

```
from osgeo import ogr
from osm2geojson import *
query="""[out:xml][timeout:60];
(
  // query part for: "building"
  way["building"](poly:"44.0602 12.5646 44.0608 12.5646 44.0612 12.5650 44.0595 12.5693 44.05860 12.5656");
);
out geom;
"""
xml = overpass_call(query)
features = xml2geojson(xml, filter_used_refs=False)
print(features)
```

**Comment by rapkin** [comment]
Oh, it's interesting. Maybe some conflict under the hood (`geos` used in Shapely and GDAL)

**Comment by valluzzi** [comment]
> Oh, it's interesting. Maybe some conflict under the hood (`geos` used in Shapely and GDAL)

Yes but only on Windows (python 3.7.9 ) (may be It is fault of the unofficial GDAL 
https://www.lfd.uci.edu/~gohlke/pythonlibs/#gdal. 
I have tried this on colab (Ubuntu ) and it works perfectly

**Comment by cgohlke** [comment]
I think this is due to an old GEOS DLL. I updated the shapely, gdal, and basemap wheels at https://www.lfd.uci.edu/~gohlke/pythonlibs to use the same geos-3.9.1 DLL. Your code works now. If you mix those wheels with binaries from pypi, conda, or osgeo, you might still run into DLL conflicts.
