### ISSUE TITLE
How to save?

### ISSUE THREAD

**Issue by seghier** [aspectumapp/osm2geojson#25]
Thanks for the script, but how to save the file from osm to geojson?
can you make it easier and convert directly with one command for example : osm2geojson.convert

**Comment by rapkin** [comment]
@CrsiX yes, you are welcome! thank you.

**Comment by CrsiX** [comment]
Is it fine for you if I change the API of some functions in the `main.py` module? Namely, I want to
a) fix typos
b) add `logger`, `area_keys` and `polygon_features` arguments to the functions that require them.
I could do that without changing the function signature by using optional arguments and simple references (that's what I'm currently doing).

Alternatively, the whole module could be restructured with a "big single" class for improved namespacing, but that obviously requires heavy changes to existing calling functions in client modules.

**Comment by rapkin** [comment]
@CrsiX yes, idea with "optional arguments" looks good

**Comment by rapkin** [comment]
Solved by https://github.com/aspectumapp/osm2geojson/pull/32
