### ISSUE TITLE
Non-Geo JSON?

### ISSUE THREAD

**Issue by xeruf** [aspectumapp/osm2geojson#36]
Any pointers on how to convert any of the common OSM formats into Overpass-like JSON in the CLI?
https://wiki.openstreetmap.org/wiki/OSM_JSON

**Comment by rapkin** [comment]
In this library we have function `parse_xml` to convert OSM XML to OSM JSON (or Overpass JSON). It should be easy to implement small CLI tool to invoke that `parse_xml` method.
