### ISSUE TITLE
Unable to download geometry data

### ISSUE THREAD

**Issue by tinder-ravitejabonagiri** [aspectumapp/osm2geojson#37]
Hey Team, thanks for the excellent library. I am facing an issue with the latest version of the library. I believe there is an issue with the [change](https://github.com/aspectumapp/osm2geojson/commit/024c06b099bc41a0c734d8435c048116c2cc3055). 

And a possible fix is: to change the check to `base_index < 0`

Please let me know if I am missing something.

**Comment by rapkin** [comment]
@tinder-ravitejabonagiri yes, it's typo, thanks

**Comment by rapkin** [comment]
Fixed in this commit https://github.com/aspectumapp/osm2geojson/commit/f5e6e0e5dbebffadbf61f75440ee382582aed948
