### ISSUE TITLE
Gaps in ways when converting to GeoJSON

### ISSUE THREAD

**Issue by ralienpp** [aspectumapp/osm2geojson#4]
We're using `osm2geojson` to retrieve route details for public transport in Moldova. There's a problem we encounter with some routes, which appear to have gaps in them, even though they look correct in OSM itself.

Here is an example:
- Go to https://overpass-turbo.eu/ and run this query `relation (7390177); >>; out geom;` - note that it looks ok and is continuous throughout the entire length (the relevant fragment is shown in the second image).
- We then take the returned XML and process it with `osm2geojson.xml2geojson()` and save it to a file.
- You can see the resulting GeoJSON here: https://github.com/roataway/infrastructure-data/blob/updated-route30/data/route_1_segments.json
- Note this gap in the image: 
![image](https://user-images.githubusercontent.com/295338/72111622-a30f5700-333b-11ea-8cc2-30d45bd2f7c4.png)

For comparison, this is what that area looks like in Overpass Turbo (the circles are speed limit signs are cameras, I believe these are not relevant in this case, but who knows...):
![image](https://user-images.githubusercontent.com/295338/72111785-11ecb000-333c-11ea-8ed5-76c34b849f70.png)

Osm2GeoJSON appears to stumble upon something, here are possibly relevant log entries from our tool:
```
 INFO - Processing single route specified by relation 7390177
 INFO - Self-intersection at or near point 28.843157115089561 47.000713289675019
Invalid geometry! Try to fix with 0 buffer
Geometry fixed!
 INFO - Done
```

And the relevant part of its source code https://github.com/roataway/infrastructure-data/blob/updated-route30/tools/getRoute#L44:
```
    with open(os.path.join(target_path, TEMPLATE_SEGMENTS % upstream_id), 'w') as f:
        geojson_segments = osm2geojson.xml2geojson(segments)
        geojson_segments = json.dumps(geojson_segments, indent=4)
        f.write(geojson_segments)
```

What is causing these gaps, and how can this be addressed?

There is a corresponding issue in our project https://github.com/roataway/infrastructure-data/issues/8, with some additional details. Note that it describes another issue besides the gaps - if you have any hints about resolving that, we'd greatly appreciate it.

Thanks!

**Comment by rapkin** [comment]
Problem was with recursive relations. I made changes to support this.

**Comment by ralienpp** [comment]
Thank you, I can confirm that the results are correct now.
