### ISSUE TITLE
The result will miss a lot geometry due to the used strategy

### ISSUE THREAD

**Issue by wuzyzy** [aspectumapp/osm2geojson#9]
I find that the result made by this tool is different from the output in [osmtogeojson](https://tyrasd.github.io/osmtogeojson/). I believe the reason is the 'used strategy' in your code. Maybe you output all geometry?

**Comment by rapkin** [comment]
Now all used refs are filtered by this block of code https://github.com/aspectumapp/osm2geojson/blob/master/osm2geojson/main.py#L76. I can make option to extract all geometries, something like this
```python
osm2geojson(some_xml, filter_used_refs=False)
```
Will be helpfull if you will provide small example for this problem

**Comment by wuzyzy** [comment]
Cool!
For the example, you can produce a overpass quried osm json in the [overpass turbo](http://overpass-turbo.eu/)
```
[out:json][bbox:50.745,7.17,50.75,7.18];
(relation[landuse];way[landuse];);
(._;>;);
out;
```
Then use ```osm2geojson.json2geojson(resopnse.json())``` to produce the geojson result.
After all you will find only 8 features are generated.
Because some way elements are a part of a relation with "role: inner".

**Comment by rapkin** [comment]
I made this option, but you will receive every node as Point. So result looks like this

![image](https://user-images.githubusercontent.com/5012778/81560220-a07c4700-9399-11ea-8f2c-8aa58f179a7d.png)
![image](https://user-images.githubusercontent.com/5012778/81560472-213b4300-939a-11ea-8eb3-b1f3f5e9fb49.png)

Is it good for you?

**Comment by wuzyzy** [comment]
Cool, then I can filter the point or line to get polygon geometry.
